### ISSUE TITLE
A user is able to schedule recurring tasks

### ISSUE THREAD

**Issue by ruibinch** [cs2103jan2016-t11-3j/main#5]
so that the user can avoid going through the hassle of repeatedly adding tasks that occur repeatedly, e.g. weekly.

**Comment by ruibinch** [comment]
and this function helps the calendar become a much more practical and useful tool.

**Comment by chongyan11** [comment]
Core adding functions: #5, #7, #20, #21

**Comment by chongyan11** [comment]
alot of other separate issues underlying have been created
