### ISSUE TITLE
Bug in undo - First undo

### ISSUE THREAD

**Issue by chongyan11** [cs2103jan2016-t11-3j/main#62]
Scenario: Start up with any number of tasks in Adult TaskFinder.
e.g. 1. Check IE2150 results
2. Read Task Analysis
3. Complete IE2130 Assignment 2

Add a task, e.g. add task 1
undo

Result:
"Check IE2150 results" gets deleted instead of "task 1", with feedback showing "Add undone".

**Comment by chongyan11** [comment]
Error does not show consistently

**Comment by ruibinch** [comment]
Fixed bug - caused by overlapping task IDs.
