### ISSUE TITLE
A user is able to add floating tasks

### ISSUE THREAD

**Issue by ruibinch** [cs2103jan2016-t11-3j/main#7]
as there might be some tasks which do not have a specific deadline.

**Comment by ruibinch** [comment]
for the user to include a deadline in the future, in the event that the due date is not known to the user yet.

**Comment by chongyan11** [comment]
Core adding functions: #5, #7, #20, #21

**Comment by ruibinch** [comment]
Done - If there is no date and time input, the task is automatically assumed as a floating task.
